import { StyleSheet } from 'react-native';

export const audioStyles = StyleSheet.create({
  container: { 
    flex: 1, 
    backgroundColor: '#F6F8FB' 
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 60,
    paddingBottom: 20,
    backgroundColor: '#F6F8FB',
  },
  headerLeft: {
    width: 48,
  },
  title: { 
    fontSize: 24, 
    fontWeight: 'bold',
    color: '#1A2366',
    flex: 1,
    textAlign: 'center',
  },
  addButton: {
    backgroundColor: '#fff',
    borderRadius: 24,
    width: 48,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  recordingCard: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 20,
    marginHorizontal: 16,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
  },
  recordingInfo: { 
    flex: 1, 
    flexDirection: 'row', 
    alignItems: 'center' 
  },
  iconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#4F8EF7',
    justifyContent: 'center',
    alignItems: 'center',
  },
  textContainer: { 
    marginLeft: 16,
    flex: 1,
  },
  recordingName: { 
    fontSize: 16, 
    fontWeight: '600',
    color: '#1A2366',
    marginBottom: 4,
  },
  recordingDuration: { 
    fontSize: 14, 
    color: '#666',
    fontWeight: '400',
  },
  recordingMetadata: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  recordingSeparator: {
    fontSize: 14,
    color: '#999',
    fontWeight: '400',
  },
  recordingSize: {
    fontSize: 14,
    color: '#999',
    fontWeight: '400',
  },
  actions: { 
    flexDirection: 'row', 
    alignItems: 'center', 
    gap: 12,
  },
  playButton: { 
    padding: 8,
    borderRadius: 20,
  },
  deleteButton: { 
    padding: 8,
    borderRadius: 20,
  },
  listContent: { 
    paddingTop: 8,
    paddingBottom: 20,
  },
  emptyListContent: {
    flex: 1,
  },
  emptyContainer: { 
    flex: 1, 
    justifyContent: 'center', 
    alignItems: 'center',
    paddingHorizontal: 40,
    paddingVertical: 60,
  },
  emptyTitle: { 
    fontSize: 24, 
    fontWeight: 'bold',
    color: '#1A2366',
    marginBottom: 8,
    textAlign: 'center',
  },
  emptySubtitle: { 
    fontSize: 16, 
    color: '#666',
    marginBottom: 32,
    textAlign: 'center',
    lineHeight: 22,
  },
  recordButton: {
    backgroundColor: '#4F8EF7',
    paddingHorizontal: 24,
    paddingVertical: 14,
    borderRadius: 24,
    flexDirection: 'row',
    alignItems: 'center',
    elevation: 3,
    shadowColor: '#4F8EF7',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  recordButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
    marginLeft: 8,
  },
  sessionNote: {
    color: '#E67E22',
    fontSize: 14,
    marginBottom: 12,
    textAlign: 'center',
    fontStyle: 'italic',
  },
  addButtonDisabled: {
    backgroundColor: '#f5f5f5',
    elevation: 1,
  },
  
  searchContainer: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: '#F6F8FB',
  },
  searchInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 12,
    paddingHorizontal: 12,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
  },
  searchIcon: {
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    paddingVertical: 12,
    fontSize: 16,
    color: '#1A2366',
  },
  clearSearchButton: {
    padding: 4,
    marginLeft: 8,
  },
  searchResults: {
    fontSize: 12,
    color: '#666',
    marginTop: 6,
    marginLeft: 4,
    fontStyle: 'italic',
  },
});